language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
# command to install dependencies
install:
- python -m pip install -e .
# command to run tests
script:
- python manage.py test_dao
